"use client";
import {useState,useMemo,useEffect} from "react";
import {ShieldCheck,LayoutDashboard,Layers,SlidersHorizontal,GitCompareArrows,Workflow,Search,Download,ArrowUpRight,LockKeyhole,FolderTree,ChevronRight,CheckCircle2,TriangleAlert, CircleHelp} from "lucide-react";
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarGroup,SidebarGroupLabel,SidebarTrigger,SidebarInset} from "@/components/ui/sidebar";
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from "@/components/ui/table";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Checkbox} from "@/components/ui/checkbox";
import {Button} from "@/components/ui/button";
import {Progress} from "@/components/ui/progress";
import {Input} from "@/components/ui/input";
import type {Snapshot,Profile,ListRecord,Check} from "@/lib/governance/types";
import {audit,inferProfile,summarize,createPlan,normalize} from "@/lib/governance/engine";
type Plan=Awaited<ReturnType<typeof createPlan>>;
const nav=[["audit","Workspace audit",LayoutDashboard],["standards","Standards library",Layers],["fields","Field inventory",SlidersHorizontal],["plans","Change plans",GitCompareArrows],["capabilities","API & automations",Workflow]] as const;
function Picker({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{id:string;name:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select>;}
function download(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function State({state}:{state:Check["state"]}){return <span className={"state "+state}>{state==="pass"?<CheckCircle2 size={13}/>:state==="drift"?<TriangleAlert size={13}/>:<CircleHelp size={13}/>} {state==="pass"?"Match":state==="drift"?"Difference":"Unknown"}</span>}
function display(v:unknown):string{if(v===null||v===undefined)return "Not observed";if(typeof v==="string")return v||"(empty)";if(typeof v==="boolean")return v?"Enabled":"Disabled";if(Array.isArray(v))return v.map(display).join(" → ");if(typeof v==="object"){const x=v as Record<string,unknown>;if(x.status)return String(x.status)+" · "+x.type+" · "+x.color;if(x.name&&x.type)return String(x.name)+" · "+x.type+" · "+(x.required===null?"required flag unknown":x.required?"required":"optional")+"\nID: "+x.id+"\nConfiguration: "+JSON.stringify(x.type_config,null,2);return JSON.stringify(v,null,2);}return String(v);}
export default function Console({snapshot,profiles}:{snapshot:Snapshot;profiles:Profile[]}){
 const [view,setView]=useState("audit"),[space,setSpace]=useState("all"),[standard,setStandard]=useState("all"),[health,setHealth]=useState("all"),[query,setQuery]=useState(""),[page,setPage]=useState(0);
 const [selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<ListRecord|null>(null),[compare,setCompare]=useState("website"),[bulk,setBulk]=useState("suggested"),[plan,setPlan]=useState<Plan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const rows=useMemo(()=>snapshot.lists.map(list=>{const suggestion=inferProfile(list);const profile=profiles.find(p=>p.id===suggestion.id);const checks=profile?audit(list,profile):[];return {list,suggestion,profile,checks,summary:summarize(checks)};}),[snapshot,profiles]);
 const filtered=rows.filter(r=>(space==="all"||r.list.spaceId===space)&&(standard==="all"||(standard==="unassigned"?!r.profile:r.profile?.id===standard))&&(health==="all"||(health==="drift"?r.summary.drift>0:health==="unknown"?r.summary.unknown>0:health==="unassigned"?!r.profile:r.summary.known>0&&r.summary.drift===0))&&normalize([r.list.name,r.list.folderName,r.list.spaceName].join(" ")).includes(normalize(query)));
 const total=summarize(filtered.flatMap(r=>r.checks)),suggested=filtered.filter(r=>r.profile).length;
 const fields=useMemo(()=>{const m=new Map<string,{field:NonNullable<ListRecord["fields"]>[number];lists:string[]}>();for(const l of snapshot.lists)for(const f of l.fields??[]){const old=m.get(f.id);if(old)old.lists.push(l.id);else m.set(f.id,{field:f,lists:[l.id]});}return [...m.values()].sort((a,b)=>a.field.name.localeCompare(b.field.name));},[snapshot]);
 const duplicateNames=new Set(fields.filter(f=>fields.some(g=>g.field.id!==f.field.id&&normalize(g.field.name)===normalize(f.field.name))).map(f=>normalize(f.field.name)));
 const workflows=new Set(snapshot.lists.map(l=>JSON.stringify(l.statuses?.map(s=>[normalize(s.status),s.type])))).size;
 useEffect(()=>setPage(0),[space,standard,health,query]);
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
  if(!context)return;const lifecycle=new AbortController();
  const tool={name:"compare_clickup_list",description:"Read a captured List and compare it to a draft standard. Does not modify ClickUp or assignments.",inputSchema:{type:"object",properties:{listId:{type:"string"},profileId:{type:"string"}},required:["listId","profileId"],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{const x=input as {listId?:string;profileId?:string};const l=snapshot.lists.find(l=>l.id===x?.listId),p=profiles.find(p=>p.id===x?.profileId);if(!l||!p)throw Error("Unknown List or profile");const checks=audit(l,p);return {listId:l.id,profile:p.name,version:p.version,summary:summarize(checks),differences:checks.filter(c=>c.state!=="pass")};}};
  try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[snapshot,profiles]);
 function openList(l:ListRecord){setCompare(inferProfile(l).id??"website");setDetail(l);}
 async function buildPlan(ids=selected,override=bulk){setError("");setBusy(true);try{const targets=ids.map(id=>{const list=snapshot.lists.find(l=>l.id===id)!;const p=profiles.find(p=>p.id===(override==="suggested"?inferProfile(list).id:override));if(!p)throw Error("Some selected Lists have no suggestion. Choose a standard for the plan.");return {list,profile:p};});setPlan(await createPlan(snapshot,targets));setView("plans");setDetail(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function toggle(id:string){setSelected(prev=>prev.includes(id)?prev.filter(x=>x!==id):[...prev,id]);}
 const current=profiles.find(p=>p.id===compare)!;
 const detailChecks=detail?audit(detail,current):[];
 const metrics=[[total.score===null?"—":total.score+"%","Draft alignment","Known checks only"],[filtered.length,"Lists in view",suggested+" with suggested standards"],[filtered.filter(r=>r.summary.drift>0).length,"Lists with differences","Against draft candidates"],[total.unknown,"Unverified checks","Excluded from alignment score"]];
 return <SidebarProvider style={{"--sidebar-width":"236px"} as React.CSSProperties}>
 <Sidebar><SidebarHeader className="brand"><span className="brand-icon"><ShieldCheck size={23}/></span><div>Control Room<small>CLICKUP ADMIN</small></div></SidebarHeader>
 <SidebarContent><div className="workspace"><span className="workspace-avatar">C</span><div>ClickUp workspace<small>{snapshot.spaces.length} Spaces · {snapshot.lists.length} Lists</small></div></div><SidebarGroup><SidebarGroupLabel>GOVERNANCE</SidebarGroupLabel><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>setView(id)} className="nav-button"><Icon/><span>{label}</span>{id==="standards"&&<span className="nav-count">6</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><div className="sidebar-note"><LockKeyhole size={18}/><strong>Observe. Compare. Plan.</strong><p>Phase 1 has no ClickUp write actions.</p></div></SidebarContent>
 <SidebarFooter><div className="snapshot-foot"><span className="tag">SNAPSHOT</span><p>{snapshot.capturedAt.slice(0,10)} · {snapshot.capturedAt.slice(11,16)} UTC</p><small>Captured through connected ClickUp</small></div></SidebarFooter></Sidebar>
 <SidebarInset><header className="topbar"><div className="flex items-center gap-3"><SidebarTrigger/><span className="subtle">Workspace</span><ChevronRight size={14}/><span>{nav.find(n=>n[0]===view)?.[1]}</span></div><span className="tag"><LockKeyhole size={12}/> Read-only</span></header>
 <main className="console-main"><div className="topline title-row"><div><p className="kicker">PHASE 01 / {view==="audit"?"WORKSPACE INTELLIGENCE":"GOVERNANCE FOUNDATION"}</p><h1>{nav.find(n=>n[0]===view)?.[1]}</h1><p className="subtle">{view==="audit"?"A clear view of configuration across your ClickUp workspace.":view==="standards"?"Six versioned candidates. Your workspace is the starting point.":view==="fields"?"Canonical field identities, options, and where they are accessible.":view==="plans"?"Review the exact scope before a future change is possible.":"Verified capabilities and the path to safe automation."}</p></div><Button variant="outline" onClick={()=>download(snapshot,"clickup-workspace-snapshot.json")}><Download size={15}/> Export snapshot</Button></div>
 {view==="audit"&&<>
 <div className="metrics">{metrics.map(([n,t,h],i)=><div className={"metric metric-"+i} key={t}><span>{t}</span><strong>{n}</strong><small>{h}</small>{i===0&&<Progress value={total.score??0} className="mt-3 h-1.5"/>}</div>)}</div>
 <div className="insight-strip"><ShieldCheck size={20}/><div><strong>A baseline to review, not approved policy</strong><p>Assignments are naming-based suggestions. Unknown settings never count as failures. {total.coverage}% of checks in this view are verifiable.</p></div><span className="tag">{workflows} status workflows</span></div>
 <section className="panel inventory"><div className="topline"><h2>List inventory <span className="count">{filtered.length}</span></h2><span className="subtle">{snapshot.spaces.length} Spaces / {snapshot.folders.length} Folders</span></div>
 <div className="filters"><div className="search-box"><Search size={17}/><Input aria-label="Search Lists" placeholder="Search Lists or Folders…" value={query} onChange={e=>setQuery(e.target.value)}/></div><Picker label="Filter by Space" value={space} onChange={setSpace} options={[{id:"all",name:"All Spaces"},...snapshot.spaces]}/><Picker label="Filter by standard" value={standard} onChange={setStandard} options={[{id:"all",name:"All standards"},...profiles,{id:"unassigned",name:"Needs classification"}]}/><Picker label="Filter by health" value={health} onChange={setHealth} options={[{id:"all",name:"All results"},{id:"drift",name:"Has differences"},{id:"match",name:"Known checks match"},{id:"unknown",name:"Has unknowns"},{id:"unassigned",name:"Needs classification"}]}/></div>
 {selected.length>0&&<div className="selection-bar"><strong>{selected.length} selected</strong><Picker label="Plan target standard" value={bulk} onChange={setBulk} options={[{id:"suggested",name:"Use each suggestion"},...profiles]}/><Button onClick={()=>buildPlan()} disabled={busy}>{busy?"Building…":"Preview change plan"}</Button><Button variant="ghost" onClick={()=>setSelected([])}>Clear</Button></div>}
 {error&&<p role="alert" className="error">{error}</p>}
 <Table><TableHeader><TableRow><TableHead className="w-10"><Checkbox aria-label="Select all filtered Lists" checked={filtered.length>0&&filtered.every(r=>selected.includes(r.list.id))} onCheckedChange={v=>setSelected(prev=>v?[...new Set([...prev,...filtered.map(r=>r.list.id)])]:prev.filter(id=>!filtered.some(r=>r.list.id===id)))}/></TableHead><TableHead>LIST / LOCATION</TableHead><TableHead>SUGGESTED STANDARD</TableHead><TableHead>ALIGNMENT</TableHead><TableHead>FINDINGS</TableHead><TableHead/></TableRow></TableHeader><TableBody>{filtered.slice(page*15,page*15+15).map(r=><TableRow key={r.list.id}><TableCell><Checkbox aria-label={"Select "+r.list.name} checked={selected.includes(r.list.id)} onCheckedChange={()=>toggle(r.list.id)}/></TableCell><TableCell><button className="list-link" onClick={()=>openList(r.list)}>{r.list.name}</button><p className="subtle location">{r.list.spaceName} <span>/</span> {r.list.folderName||"Folderless"}</p></TableCell><TableCell>{r.profile?<><span className="standard-label">{r.profile.name}</span><small className="block subtle">Draft v{r.profile.version} · suggested</small></>:<span className="state unknown">Needs classification</span>}</TableCell><TableCell>{r.profile?<div className="alignment"><strong>{r.summary.score??"—"}%</strong><Progress value={r.summary.score??0}/></div>:<span className="subtle">Not assessed</span>}</TableCell><TableCell>{r.profile?<><span className={r.summary.drift?"finding":"good"}>{r.summary.drift} differences</span><small className="block subtle">{r.summary.unknown} unknown</small></>:<span className="subtle">Choose a standard</span>}</TableCell><TableCell><Button size="icon" variant="ghost" aria-label={"Inspect "+r.list.name} onClick={()=>openList(r.list)}><ChevronRight size={17}/></Button></TableCell></TableRow>)}</TableBody></Table>
 {!filtered.length&&<div className="empty"><Search/><h2>No Lists match these filters</h2><Button variant="outline" onClick={()=>{setSpace("all");setStandard("all");setHealth("all");setQuery("");}}>Reset filters</Button></div>}
 <div className="table-footer"><span>Showing {filtered.length? page*15+1:0}–{Math.min((page+1)*15,filtered.length)} of {filtered.length} Lists</span><div className="flex gap-2"><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button variant="outline" disabled={(page+1)*15>=filtered.length} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div></section>
 <p className="coverage-note">Snapshot of accessible locations returned by ClickUp. Archived or inaccessible locations may be excluded. Space settings, parent status overrides, views, and native automation definitions are not exposed by this connection.</p>
 </>}
 {view==="standards"&&<><div className="insight-strip"><Layers size={22}/><div><strong>All profiles are draft v1.0.0</strong><p>Comparison changes only this view. No standard is assigned to ClickUp. Publish a new config version to evolve a profile.</p></div></div><div className="profile-grid">{profiles.map(p=><section className="panel profile-card" key={p.id}><div className="topline"><span className="profile-icon"><Layers size={20}/></span><span className="tag">DRAFT · {p.version}</span></div><h2>{p.name}</h2><p className="subtle">{p.description}</p><dl><dt>Seed List</dt><dd>{p.sourceListName}</dd><dt>Workflow</dt><dd>{p.statuses.length} statuses</dd><dt>Canonical fields</dt><dd>{p.fields.length} fields</dd><dt>Suggested Lists</dt><dd>{rows.filter(r=>r.profile?.id===p.id).length}</dd></dl><div className="status-cloud">{p.statuses.slice(0,5).map(s=><span key={s.status}>{s.status}</span>)}{p.statuses.length>5&&<span>+{p.statuses.length-5}</span>}</div><div className="flex gap-2 mt-5"><Button variant="outline" onClick={()=>{setStandard(p.id);setSpace("all");setHealth("all");setQuery("");setView("audit");}}>Review Lists</Button><Button variant="ghost" onClick={()=>download(p,p.id+"-v"+p.version+".json")}><Download size={14}/> Profile</Button></div></section>)}</div></>}
 {view==="fields"&&<><div className="metrics">{[[fields.length,"Unique field IDs"],[duplicateNames.size,"Names with multiple IDs"],[snapshot.workspaceFields?.length??0,"Workspace-level fields"],[snapshot.lists.filter(l=>l.fields!==null).length,"Lists with field data"]].map(([n,t])=><div className="metric" key={t}><strong>{n}</strong><span>{t}</span></div>)}</div><Tabs defaultValue="catalog"><TabsList><TabsTrigger value="catalog">Field catalog</TabsTrigger><TabsTrigger value="scopes">Spaces & Folders</TabsTrigger></TabsList><TabsContent value="catalog"><section className="panel"><p className="subtle mb-5">Same name does not mean same field. Accessible field counts include inherited fields. Options and required flags are available in each List’s detail.</p><Table><TableHeader><TableRow><TableHead>FIELD</TableHead><TableHead>TYPE</TableHead><TableHead>ACCESSIBLE ON</TableHead><TableHead>IDENTITY</TableHead></TableRow></TableHeader><TableBody>{fields.map(({field,lists})=><TableRow key={field.id}><TableCell><strong>{field.name}</strong>{duplicateNames.has(normalize(field.name))&&<small className="block finding">Duplicate name</small>}</TableCell><TableCell>{field.type}<small className="block subtle">{field.required===null?"Required flag unknown":field.required?"Required":"Optional"}</small></TableCell><TableCell><button className="list-link" onClick={()=>openList(snapshot.lists.find(l=>l.id===lists[0])!)}>{lists.length} Lists</button></TableCell><TableCell><code className="subtle">{field.id}</code></TableCell></TableRow>)}</TableBody></Table></section></TabsContent><TabsContent value="scopes"><section className="panel"><h2>Hierarchy inventory</h2><p className="subtle mb-4">Empty Spaces and Folders are included. Scope fields can include inherited workspace fields.</p>{snapshot.spaces.map(s=><details key={s.id} className="scope-row"><summary><FolderTree size={16}/><strong>{s.name}</strong><span>{snapshot.lists.filter(l=>l.spaceId===s.id).length} Lists · {s.fields?.length??"?"} fields</span></summary><p className="subtle">Space ID: {s.id} · Settings: not exposed by connector</p><div className="status-cloud">{s.fields?.map(f=><span key={f.id} title={f.id}>{f.name} · {f.type}</span>)}</div>{snapshot.folders.filter(f=>f.spaceId===s.id).map(f=><div className="folder-row" key={f.id}><strong>{f.name}</strong><small>{snapshot.lists.filter(l=>l.folderId===f.id).length} Lists · {f.fields?.length??"?"} accessible fields</small></div>)}</details>)}</section></TabsContent></Tabs></>}
 {view==="plans"&&<><div className="insight-strip"><LockKeyhole size={21}/><div><strong>Every plan is a dry run</strong><p>Plans contain before snapshots, profile versions, configuration hashes, unknowns, and manual steps. Applying is disabled at the code level.</p></div></div>{error&&<p className="error" role="alert">{error}</p>}{!plan?<section className="panel empty"><GitCompareArrows size={36}/><h2>No change plan yet</h2><p>Select Lists in the audit, choose a standard, and preview the differences.</p><Button onClick={()=>setView("audit")}>Choose Lists</Button></section>:<section className="panel"><div className="topline"><div><h2>{plan.items.length} Lists in this plan</h2><p className="subtle">{plan.items.reduce((n,i)=>n+i.findings.length,0)} review items · {plan.createdAt.slice(0,19).replace("T"," ")} UTC</p></div><Button onClick={()=>download(plan,"clickup-change-plan.json")}><Download size={15}/> Export plan</Button></div><div className="plan-guard"><strong>Apply Standard is unavailable in Phase 1.</strong><p>{plan.guards.join(" · ")}</p></div>{plan.items.map(i=><details className="scope-row" key={i.listId}><summary><strong>{i.listName}</strong><span>{i.findings.length} review items</span></summary><p className="subtle">Draft {i.profile.id} v{i.profile.version} · All operations non-executable</p>{i.findings.map(f=><div className="plan-finding" key={f.key}><State state={f.state}/><strong>{f.label}</strong><span>{f.action} · {f.risk} risk</span><p>{f.reason}</p></div>)}{!i.findings.length&&<p>No differences in assessed checks.</p>}</details>)}<p className="coverage-note">{plan.rollback}</p></section>}</>}
 {view==="capabilities"&&<><section className="panel"><div className="topline"><h2>What this connection can do</h2><span className="tag">Verified September 17, 2026</span></div><p className="subtle my-4">The connected session exposes no Unified API operators. Public API support and availability through this connector are separate.</p><Table><TableHeader><TableRow><TableHead>CAPABILITY</TableHead><TableHead>CONNECTED TOOLS</TableHead><TableHead>PUBLIC API / PHASE 2</TableHead></TableRow></TableHeader><TableBody>{[
 ["Hierarchy, List statuses, field definitions","Read available · captured","Read available"],
 ["List name and description","Write tools exist · unused","Writable; future reviewed executor"],
 ["Task status and custom field values","Write tools exist · unused","Writable; task changes, not schema changes"],
 ["List status workflow / field schema","No management tools exposed","No documented general List workflow or field-schema write endpoint found"],
 ["Space ClickApps and views","Not exposed","Documented Space settings and View APIs; separate authenticated adapter"],
 ["Native automation rules and packages","No inventory or write tools","No native rule CRUD endpoint found in official API index"],
 ["Webhook subscriptions","Not exposed","Create, list, update and delete via public API; not registered in Phase 1"]
 ].map(([a,b,c])=><TableRow key={a}><TableCell><strong>{a}</strong></TableCell><TableCell>{b}</TableCell><TableCell>{c}</TableCell></TableRow>)}</TableBody></Table><div className="callout">The List API’s “status” parameter changes the List color. It does not replace the task status workflow.</div></section>
 <section className="panel mt-6"><h2>Webhook / rule-engine foundation</h2><div className="flow">{["Signed ClickUp event","Verify & deduplicate","Match versioned rules","Create dry-run intent","Approved future executor"].map((t,i)=><div key={t}><small>0{i+1}</small><strong>{t}</strong></div>)}</div><p>Rule contracts, signature verification, and dry-run evaluation are included. No webhook is registered and no event receiver or task-action executor is enabled.</p><p className="subtle mt-3">Production activation still needs a durable event inbox, queues, retries, loop protection, per-workspace access, secret storage, and explicit approval of executable actions.</p><div className="source-links"><a href="https://developer.clickup.com/llms.txt" target="_blank" rel="noreferrer">Official API index <ArrowUpRight size={14}/></a><a href="https://developer.clickup.com/docs/webhooks" target="_blank" rel="noreferrer">Webhooks <ArrowUpRight size={14}/></a><a href="https://developer.clickup.com/reference/updatelist" target="_blank" rel="noreferrer">List API <ArrowUpRight size={14}/></a></div></section>
 <section className="panel mt-6"><h2>Snapshot & setup</h2><p className="mt-3">This console runs from the captured workspace dataset. It is not continuously synchronized. Setup instructions include a read-only API importer for future refreshes; your ChatGPT connector credentials are not embedded in this app.</p><p className="subtle mt-3">Data collection: {snapshot.lists.length} List details, {snapshot.lists.filter(l=>l.fields).length} List field inventories, {snapshot.spaces.length} Space scopes, {snapshot.folders.length} Folder scopes, and workspace fields. Task contents were not collected.</p></section></>}
 </main></SidebarInset>
 <Sheet open={!!detail} onOpenChange={v=>{if(!v)setDetail(null);}}><SheetContent className="detail-sheet w-full sm:max-w-[860px] overflow-y-auto">{detail&&<><SheetHeader><p className="kicker">LIST INSPECTOR</p><SheetTitle className="text-2xl pr-6">{detail.name}</SheetTitle><SheetDescription>{detail.spaceName} / {detail.folderName||"Folderless"} · {detail.id}</SheetDescription></SheetHeader><div className="detail-body"><div className="topline"><div><p className="subtle mb-2">Compare with draft standard</p><Picker label="Comparison standard" value={compare} onChange={setCompare} options={profiles}/></div><a className="external" href={detail.url||"https://app.clickup.com/"+snapshot.workspaceId+"/v/l/li/"+detail.id} target="_blank" rel="noreferrer">Open in ClickUp <ArrowUpRight size={15}/></a></div><div className="detail-score"><strong>{summarize(detailChecks).score??"—"}%</strong><div>alignment on known checks<p>{summarize(detailChecks).drift} differences · {summarize(detailChecks).unknown} unknown</p></div><span className="tag">Draft v{current.version}</span></div>
 <Tabs defaultValue="diff"><TabsList><TabsTrigger value="diff">Side-by-side diff</TabsTrigger><TabsTrigger value="observed">Observed configuration</TabsTrigger></TabsList><TabsContent value="diff"><p className="subtle my-4">Profile comparison only. Unknowns require inspection; extra statuses are retained until a reviewed task mapping exists.</p><div className="diff-head"><span>CAPTURED IN CLICKUP</span><span>{current.name.toUpperCase()} · V{current.version}</span></div>{detailChecks.map(c=><div className={"diff-row "+c.state} key={c.key}><div className="diff-label"><strong>{c.label}</strong><State state={c.state}/></div><div className="diff-values"><pre>{display(c.actual)}</pre><pre>{display(c.expected)}</pre></div><p>{c.reason}</p></div>)}</TabsContent><TabsContent value="observed"><h2 className="mt-6 mb-3">Effective statuses</h2><div className="status-cloud">{detail.statuses?.map(s=><span key={s.id||s.status}><i style={{background:s.color}}/>{s.status} · {s.type}</span>)??"Unavailable"}</div><h2 className="mt-6 mb-3">Accessible custom fields</h2>{detail.fields?.map(f=><details className="scope-row" key={f.id}><summary><strong>{f.name}</strong><span>{f.type}</span></summary><p className="subtle">{f.id} · {f.required===null?"Required flag unknown":f.required?"Required":"Optional"}</p><pre className="config-json">{JSON.stringify(f.type_config,null,2)}</pre></details>)??"Unavailable"}<h2 className="mt-6">Settings</h2><pre className="config-json">{JSON.stringify(detail.settings,null,2)}</pre></TabsContent></Tabs><Button className="mt-6 w-full" disabled={busy} onClick={()=>buildPlan([detail.id],compare)}><GitCompareArrows size={16}/> Preview this List’s change plan</Button>{error&&<p role="alert" className="error">{error}</p>}</div></>}</SheetContent></Sheet>
 </SidebarProvider>;
}
