"use client";
import {useEffect,useState} from "react";
import type {Snapshot,ListRecord} from "@/lib/governance/types";
import {activityFlag,type ActivityReport} from "@/lib/governance/staleness";
import {reviewLabels,type Review,type ControlState,type ReviewEvent} from "@/lib/control-room/types";
import {reviewDue,todayInNewYork} from "@/lib/control-room/review-queue";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from "@/components/ui/table";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {readableTime} from "./sync-workspace";
export default function ReviewQueue({snapshot,activity,state,onRefresh,onOpen,initialFilter="all",focusId}:{snapshot:Snapshot;activity:ActivityReport;state:ControlState|null;onRefresh:()=>Promise<void>;onOpen:(l:ListRecord)=>void;initialFilter?:string;focusId?:string}){
 const [search,setSearch]=useState(""),[space,setSpace]=useState("all"),[filter,setFilter]=useState(initialFilter),[page,setPage]=useState(0);
 const [editing,setEditing]=useState<ListRecord|null>(()=>snapshot.lists.find(l=>l.id===focusId)??null);
 const reviews=new Map(state?.reviews.map(r=>[r.listId,r])??[]),today=todayInNewYork();
 const rows=snapshot.lists.map(list=>({list,review:reviews.get(list.id),flag:activityFlag(activity.activity[list.id],activity.checkedAt,activity.complete)})).filter(r=>{
  return (space==="all"||r.list.spaceId===space)&&[r.list.name,r.list.spaceName,r.list.folderName,r.review?.owner].join(" ").toLowerCase().includes(search.toLowerCase())&&
  (filter==="all"||(filter==="due"?reviewDue(r.review,today):filter==="stale_unreviewed"?((r.flag==="warning"||r.flag==="critical")&&(!r.review||r.review.status==="unreviewed")):filter==="stale"?(r.flag==="warning"||r.flag==="critical"):(r.review?.status??"unreviewed")===filter));
 }).sort((a,b)=>Number(reviewDue(b.review,today))-Number(reviewDue(a.review,today))||Number(b.flag==="critical")-Number(a.flag==="critical")||a.list.name.localeCompare(b.list.name));
 const change=(fn:(v:string)=>void)=>(e:React.ChangeEvent<HTMLSelectElement|HTMLInputElement>)=>{fn(e.target.value);setPage(0);};
 return <><p className="coverage-note mb-4">These decisions are saved in the control room. “Archive candidate” never archives a List in ClickUp. Owners are review labels; no assignment or notification is sent.</p>
 <section className="panel inventory"><div className="topline"><h2>List lifecycle reviews <span className="count">{rows.length}</span></h2></div><div className="filters">
 <Input aria-label="Search review queue" placeholder="Search List, location or review owner…" value={search} onChange={change(setSearch)} className="max-w-sm"/>
 <select className="native-select" aria-label="Review Space" value={space} onChange={change(setSpace)}><option value="all">All Spaces</option>{snapshot.spaces.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>
 <select className="native-select" aria-label="Review status filter" value={filter} onChange={change(setFilter)}><option value="all">All Lists</option><option value="due">Follow-up due</option><option value="stale_unreviewed">Stale · not reviewed</option><option value="stale">Flagged for inactivity</option>{Object.entries(reviewLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>
 </div><Table><TableHeader><TableRow><TableHead>LIST / LOCATION</TableHead><TableHead>ACTIVITY</TableHead><TableHead>DECISION</TableHead><TableHead>OWNER / FOLLOW-UP</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.slice(page*20,page*20+20).map(({list,review,flag})=><TableRow key={list.id}><TableCell><button className="list-link" onClick={()=>onOpen(list)}>{list.name}</button><p className="subtle location">{list.spaceName} / {list.folderName||"Folderless"}</p></TableCell><TableCell><span className={"state "+(flag==="critical"?"critical":flag==="warning"?"drift":flag==="recent"?"pass":"unknown")}>{flag==="critical"?"Over 12 months":flag==="warning"?"Over 6 months":flag==="recent"?"Recent":"Unknown"}</span></TableCell><TableCell>{reviewLabels[review?.status??"unreviewed"]}{review?.reason&&<p className="subtle review-reason">{review.reason}</p>}</TableCell><TableCell>{review?.owner||"No owner"}<small className={"block "+(reviewDue(review,today)?"finding":"subtle")}>{review?.reviewDate?(reviewDue(review,today)?"Due: ":"Follow-up: ")+review.reviewDate:"No follow-up date"}</small></TableCell><TableCell><Button variant="outline" onClick={()=>setEditing(list)} aria-label={"Review "+list.name}>Review</Button></TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&<div className="empty"><h2>No Lists match</h2><Button variant="outline" onClick={()=>{setSearch("");setSpace("all");setFilter("all");setPage(0);}}>Reset filters</Button></div>}
 <div className="table-footer"><span>{rows.length?page*20+1:0}–{Math.min((page+1)*20,rows.length)} of {rows.length}</span><div className="flex gap-2"><Button variant="outline" disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button variant="outline" disabled={(page+1)*20>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div></section>
 <Sheet open={!!editing} onOpenChange={open=>{if(!open)setEditing(null)}}><SheetContent className="detail-sheet w-full sm:max-w-[600px] overflow-y-auto">{editing&&<><SheetHeader><SheetTitle>Review {editing.name}</SheetTitle><SheetDescription>{editing.spaceName} / {editing.folderName||"Folderless"}</SheetDescription></SheetHeader><div className="detail-body"><ReviewEditor key={editing.id} list={editing} saved={reviews.get(editing.id)} enabled={state?.storage==="ready"} onRefresh={onRefresh}/></div></>}</SheetContent></Sheet></>;
}
function ReviewEditor({list,saved,enabled,onRefresh}:{list:ListRecord;saved:Review|undefined;enabled:boolean;onRefresh:()=>Promise<void>}){
 const [status,setStatus]=useState(saved?.status??"unreviewed"),[owner,setOwner]=useState(saved?.owner??""),[reason,setReason]=useState(saved?.reason??""),[date,setDate]=useState(saved?.reviewDate??""),[version,setVersion]=useState(saved?.version??0),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[conflict,setConflict]=useState(false);
 const [events,setEvents]=useState<ReviewEvent[]>([]),[historyError,setHistoryError]=useState("");
 async function history(){try{const r=await fetch("/api/reviews?listId="+list.id);const d=await r.json() as {events:ReviewEvent[]};if(!r.ok)throw Error();setEvents(d.events);setHistoryError("");}catch{setHistoryError("History is unavailable. Try reopening this review.");}}
 useEffect(()=>{if(enabled)void history();},[list.id,enabled]); // eslint-disable-line react-hooks/exhaustive-deps
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{
  const r=await fetch("/api/reviews",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({listId:list.id,status,owner,reason,reviewDate:date||null,version})});const d=await r.json() as {error?:string;review:Review};
  if(!r.ok){if(r.status===409)setConflict(true);throw Error(d.error||"Save failed");}
  setVersion(d.review.version);setMessage("Decision saved.");await onRefresh();await history();
 }catch(e){setMessage(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
 function reload(){setStatus(saved?.status??"unreviewed");setOwner(saved?.owner??"");setReason(saved?.reason??"");setDate(saved?.reviewDate??"");setVersion(saved?.version??0);setConflict(false);setMessage("Loaded the latest saved decision.");}
 return <><form className="review-form" onSubmit={save}><label>Decision<select value={status} onChange={e=>setStatus(e.target.value as Review["status"])} className="native-select">{Object.entries(reviewLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Review owner<Input value={owner} onChange={e=>setOwner(e.target.value)} maxLength={120} placeholder="Person responsible for follow-up"/></label><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} required={status!=="unreviewed"} rows={4} placeholder="Why should this List remain active or be reviewed?"/></label><label>Follow-up date<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>
 {!enabled&&<p className="callout">Database connection required to save decisions.</p>}<Button type="submit" disabled={!enabled||busy||conflict}>{busy?"Saving…":"Save decision"}</Button>{conflict&&<Button type="button" variant="outline" onClick={async()=>{await onRefresh();setMessage("Latest review refreshed. Click Load latest decision to replace your draft.");}}>Refresh latest review</Button>}{conflict&&<Button type="button" variant="outline" onClick={reload}>Load latest decision</Button>}{message&&<p role="status" className="subtle">{message}</p>}</form>
 <h2 className="mt-6">Decision history</h2><p className="subtle">Saved by the signed-in admin account. Shared credentials identify the account, not individual people.</p>{historyError&&<p role="alert">{historyError}</p>}{!events.length&&!historyError&&<p className="subtle mt-3">No saved decisions yet.</p>}{events.map(event=><article key={event.id} className="review-event"><strong>{reviewLabels[event.after.status]}</strong><p>{event.after.reason||"No reason recorded"}</p><small>{event.after.owner||"No owner"} · {event.after.reviewDate||"No follow-up date"}</small><p className="subtle">{readableTime(event.at)} ET · {event.actor}</p></article>)}</>;
}
