"use client";
import {useState} from "react";
import type {Snapshot,ListRecord} from "@/lib/governance/types";
import {activityFlag,type ActivityReport} from "@/lib/governance/staleness";
import {Table,TableHeader,TableHead,TableRow,TableBody,TableCell} from "@/components/ui/table";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Input} from "@/components/ui/input";
import {Button} from "@/components/ui/button";
const labels={critical:"Over 12 months",warning:"Over 6 months",recent:"Within 6 months",unknown:"Unknown"};
const rank={critical:0,warning:1,unknown:2,recent:3};
const date=(s:string|null|undefined)=>s?new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeZone:"America/New_York"}).format(new Date(s)):"Not available";
export default function StaleLists({snapshot,report,onOpen}:{snapshot:Snapshot;report:ActivityReport;onOpen:(l:ListRecord)=>void}){
 const [space,setSpace]=useState("all"),[flag,setFlag]=useState("flagged"),[search,setSearch]=useState(""),[page,setPage]=useState(0);
 const [sort,setSort]=useState("severity");
 const all=snapshot.lists.map(list=>({list,activity:report.activity[list.id],flag:activityFlag(report.activity[list.id],report.checkedAt,report.complete)}));
 const scoped=all.filter(r=>(space==="all"||r.list.spaceId===space)&&[r.list.name,r.list.spaceName,r.list.folderName].join(" ").toLowerCase().includes(search.toLowerCase()));
 const rows=scoped.filter(r=>flag==="all"||(flag==="flagged"?(r.flag==="critical"||r.flag==="warning"):r.flag===flag)).sort((a,b)=>{if(sort==="name")return a.list.name.localeCompare(b.list.name);const x=a.activity?.lastActivityAt,y=b.activity?.lastActivityAt;if(!x&&y)return 1;if(x&&!y)return -1;return (sort==="severity"?rank[a.flag]-rank[b.flag]:0)||(x??"").localeCompare(y??"")*(sort==="newest"?-1:1)||a.list.name.localeCompare(b.list.name)});
 const change=(fn:(s:string)=>void)=>(s:string)=>{fn(s);setPage(0)};
 function exportRows(){const value={checkedAt:report.checkedAt,scope:report.scope,thresholds:"Strictly older than 6 / 12 calendar months at collection time (UTC)",lists:rows.map(r=>({id:r.list.id,name:r.list.name,space:r.list.spaceName,folder:r.list.folderName,lastTaskUpdate:r.activity?.lastActivityAt??null,flag:labels[r.flag],tasksScanned:r.activity?.tasksScanned??0}))};const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="clickup-stale-lists.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="metrics">{(["critical","warning","recent","unknown"] as const).map(f=><div className="metric" key={f}><span>{labels[f]}</span><strong style={{color:f==="critical"?"#b42318":f==="warning"?"#a65d14":undefined}}>{scoped.filter(r=>r.flag===f).length}</strong><small>{f==="critical"?"Priority review":f==="warning"?"Review for inactivity":f==="unknown"?"Not classified as stale":"Observed task updates"}</small></div>)}</div>
 <div className="insight-strip"><div><strong>Last activity = last observed task update</strong><p>Checked {date(report.checkedAt)}. Flags are assessed at collection time, not against an aging snapshot. Closed tasks and subtasks are included. List-only edits and comments not reflected in task timestamps are not independently measured.</p></div></div>
 <section className="panel inventory"><div className="topline"><h2>Stale Lists <span className="count">{rows.length}</span></h2><Button variant="outline" onClick={exportRows}>Export results</Button></div><div className="filters">
 <Input className="max-w-sm" aria-label="Search stale Lists" placeholder="Search Lists, Folders or Spaces…" value={search} onChange={e=>change(setSearch)(e.target.value)}/>
 <Select value={space} onValueChange={change(setSpace)}><SelectTrigger aria-label="Activity Space filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All Spaces</SelectItem>{snapshot.spaces.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select>
 <Select value={flag} onValueChange={change(setFlag)}><SelectTrigger aria-label="Activity flag filter"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="flagged">All flagged Lists</SelectItem><SelectItem value="all">All Lists</SelectItem>{Object.entries(labels).map(([id,name])=><SelectItem value={id} key={id}>{name}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={change(setSort)}><SelectTrigger aria-label="Sort stale Lists"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="severity">Flag severity</SelectItem><SelectItem value="oldest">Oldest activity first</SelectItem><SelectItem value="newest">Newest activity first</SelectItem><SelectItem value="name">List name</SelectItem></SelectContent></Select></div>
 <Table><TableHeader><TableRow><TableHead>LIST / LOCATION</TableHead><TableHead>LAST TASK UPDATE</TableHead><TableHead>INACTIVITY FLAG</TableHead><TableHead>TASKS SCANNED</TableHead></TableRow></TableHeader><TableBody>{rows.slice(page*25,page*25+25).map(r=><TableRow key={r.list.id}><TableCell><button className="list-link" onClick={()=>onOpen(r.list)}>{r.list.name}</button><p className="subtle location">{r.list.spaceName} / {r.list.folderName||"Folderless"}</p></TableCell><TableCell>{date(r.activity?.lastActivityAt)}{r.activity?.lastActivityAt&&report.checkedAt&&<small className="block subtle">{Math.max(0,Math.floor((Date.parse(report.checkedAt)-Date.parse(r.activity.lastActivityAt))/86400000))} days at capture</small>}</TableCell><TableCell><span className={"state "+(r.flag==="critical"?"critical":r.flag==="warning"?"drift":r.flag==="recent"?"pass":"unknown")}>{labels[r.flag]}</span>{r.flag==="unknown"&&<small className="block subtle">{!report.complete?"Activity collection incomplete":!r.activity?"No accessible task activity":r.activity.missingDates?"Some task dates unavailable":"No usable date"}</small>}</TableCell><TableCell>{report.complete?r.activity?.tasksScanned??0:"—"}</TableCell></TableRow>)}</TableBody></Table>
 {!rows.length&&<div className="empty"><h2>No Lists match these filters</h2><Button variant="outline" onClick={()=>{setFlag("all");setSpace("all");setSearch("");setPage(0)}}>Show all Lists</Button></div>}
 <div className="table-footer"><span>{rows.length? page*25+1:0}–{Math.min((page+1)*25,rows.length)} of {rows.length}</span><div className="flex gap-2"><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Button><Button variant="outline" disabled={(page+1)*25>=rows.length} onClick={()=>setPage(p=>p+1)}>Next</Button></div></div></section>
 <p className="coverage-note">{report.scope} The List inventory was captured {date(snapshot.capturedAt)}. Red and amber flags are review signals; nothing is archived or deleted.</p></>;
}
